name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: restore cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ env.cache-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version-file: '.node-version'
    - name: Install yarn
      run: npm i -g yarn@1.22.10
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint
    - name: Run stylelint
      run: yarn stylelint src/**/*\[\.s*css\|\.vue\]
